# Generated by Django 2.0 on 2019-11-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.CharField(max_length=20)),
                ('CODE', models.CharField(max_length=20)),
                ('GRADE', models.IntegerField(default=0)),
                ('CALSS', models.CharField(max_length=10)),
            ],
        ),
    ]
