# Generated by Django 2.0 on 2019-11-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERID', models.CharField(max_length=20)),
                ('CONTENT', models.CharField(max_length=100)),
            ],
        ),
    ]
