# Generated by Django 2.0 on 2019-12-01 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_gr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gr',
            old_name='USERID',
            new_name='USEREMAIL',
        ),
    ]
