# Generated by Django 2.0 on 2019-12-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20191201_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSEIntenCoNonSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.CharField(max_length=20)),
                ('CONTENT', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CSEIntenCoSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.CharField(max_length=20)),
                ('CODE', models.CharField(max_length=20)),
                ('CLASS', models.CharField(max_length=20)),
                ('GRADE', models.IntegerField(default=0)),
            ],
        ),
    ]
