# Generated by Django 2.0 on 2019-12-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_cseintencononsubject_cseintencosubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='USEREMAIL',
            field=models.CharField(default='NULL', max_length=20),
        ),
    ]
