# Generated by Django 2.0 on 2019-12-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_subject_useremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cseintencosubject',
            name='ISDESIGN',
            field=models.BooleanField(default=False),
        ),
    ]
