# Generated by Django 2.0 on 2019-12-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_cseintencosubject_isdesign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='CALSS',
            new_name='CLASS',
        ),
    ]
