# Generated by Django 2.0 on 2019-12-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='MAJOR',
            field=models.CharField(default='N', max_length=20),
        ),
    ]
