# Generated by Django 2.0 on 2019-12-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_user_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USEREMAIL', models.CharField(max_length=100)),
                ('TITLE', models.CharField(max_length=100)),
                ('DESC', models.CharField(max_length=1000)),
            ],
        ),
    ]
