# Generated by Django 2.0 on 2019-12-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='DESC',
            field=models.TextField(max_length=1000),
        ),
    ]
