# Generated by Django 2.0 on 2019-12-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_auto_20191202_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSWCoNonSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.CharField(max_length=20)),
                ('CONTENT', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalSWCoSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.CharField(max_length=20)),
                ('CODE', models.CharField(max_length=20)),
                ('CLASS', models.CharField(max_length=20)),
                ('GRADE', models.IntegerField(default=0)),
            ],
        ),
    ]
