# Generated by Django 2.0 on 2019-12-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_globalswcononsubject_globalswcosubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalswcononsubject',
            name='TRACK',
            field=models.CharField(default='N', max_length=20),
        ),
    ]
