# Generated by Django 2.0 on 2019-12-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_auto_20191215_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSEIntenCoStudentId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STUDENT_ID', models.CharField(max_length=20)),
                ('TOTAL_GRADE', models.IntegerField(default=0)),
                ('ENGINEER_CUL_GRADE', models.IntegerField(default=0)),
                ('BASEMAJOR_GRADE', models.IntegerField(default=0)),
                ('MAJOR_GRADE', models.IntegerField(default=0)),
                ('ABEEK_GRADE', models.IntegerField(default=0)),
            ],
        ),
    ]
