# Generated by Django 2.0 on 2019-12-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_cseintencostudentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cseintencostudentid',
            name='DESIGN_GRADE',
            field=models.IntegerField(default=0),
        ),
    ]
