# Generated by Django 2.0 on 2019-12-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_cseintencostudentid_design_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cseintencostudentid',
            name='ENG_GRADE',
            field=models.CharField(default='N', max_length=20),
        ),
        migrations.AddField(
            model_name='cseintencostudentid',
            name='INTERN_GRADE',
            field=models.CharField(default='N', max_length=20),
        ),
    ]
