# Generated by Django 2.0 on 2019-12-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0022_question_isfaq'),
    ]

    operations = [
        migrations.CreateModel(
            name='SWConnSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.CharField(max_length=20)),
                ('CATEGORY', models.CharField(max_length=20)),
                ('CLASS', models.CharField(max_length=20)),
                ('GRADE', models.IntegerField(default=0)),
                ('CODE', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='TRACK_CATEGORY',
            field=models.CharField(default='N', max_length=20),
        ),
    ]
