# Generated by Django 2.0 on 2019-12-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0023_auto_20191216_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='CATEGORY',
            field=models.CharField(default='N', max_length=10),
        ),
    ]
