# Generated by Django 2.0 on 2019-12-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0025_auto_20191218_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QUESTION_ID', models.IntegerField(default=0)),
                ('TITLE', models.CharField(max_length=100)),
                ('DESC', models.TextField(max_length=1000)),
                ('ANSWER', models.TextField(max_length=1000)),
                ('ISFAQ', models.BooleanField(default=False)),
                ('ISANSWERED', models.BooleanField(default=False)),
            ],
        ),
    ]
