# Generated by Django 2.0 on 2019-12-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0026_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
