# Generated by Django 2.0 on 2019-12-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0027_auto_20191218_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='TITLE',
            field=models.CharField(default='N', max_length=100),
        ),
    ]
