# Generated by Django 2.0 on 2019-12-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0028_auto_20191218_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='USEREMAIL',
            field=models.CharField(default='N', max_length=100),
        ),
    ]
